Update sponge to export truncated hash
dusk-network/Poseidon252 pull request #168
Opened 2021-12-17 11:50 UTC by vlopes11

Resolves #167

2021-12-20 14:21 UTC, moCello commented on src/sponge/truncated.rs
> +use dusk_jubjub::JubJubScalar;
Why do you specifically import `JubJubScalar` here? afaik it should be included in `dusk_plonk::prelude::*` which we need for other types anyway.

2021-12-20 15:33 UTC, ureeves commented on src/sponge/truncated.rs
>  use dusk_plonk::prelude::*;
Unused import

2021-12-22 00:50 UTC, ZER0 requested changes
I don't think I agreed with the public API here, it also seems another PR was landed before this one that substantially change the API in the opposite way it was designed for.

Specifically here I'm referring to the `sponge.rs`  that re-export `truncated::hash` as `truncated_hash` where we intentionally refactored in the past `Poseidon252` to avoid such things; so it looks like we're doing a step back in that direction.

2021-12-22 13:24 UTC, ZER0 approved these changes

2021-12-22 16:42 UTC, merged